In [95]:
import numpy as np
import pandas as pd
from sklearn import linear_model

df = pd.read_csv("experience.csv")
df

   experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [96]:
df["experience"].fillna(0)

median = df["experience"].median()
median

df["test_score"] = df["test_score"].fillna(1)

df["experience"] = df["experience"].fillna(median)
df

   experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         1.0                7   72000
7        11.0         7.0                8   80000

In [99]:
regression = linear_model.LinearRegression()

regression.fit(
    df[["experience", "test_score", "interview_score"]],
    df["salary"]
)

coefficient = regression.coef_
intercept = regression.intercept_

coefficient : [2722.87951629   84.28517849 2934.02434451] , intercept: 22286.565060747613
prediction for 5 years, 7 test score , 6 interview score: salary = [54095.10495869]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [100]:
prediction = regression.predict([[5,7,6]])
print(f"coefficient : {coefficient} , intercept: {intercept}")
print(f"prediction for 5 years, 7 test score , 6 interview score: salary = {prediction}")

coefficient : [2722.87951629   84.28517849 2934.02434451] , intercept: 22286.565060747613
prediction for 5 years, 7 test score , 6 interview score: salary = [54095.10495869]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(